pipeline {
    agent any
    stages {
        stage('Example') {
           // input {
             //   message "Should we continue?"
               // ok "Yes, we should."
                //submitter "alice,bob"
                //parameters {
                    //string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                  //  choice(name: 'CHOICES', choices: ['one', 'two'], description: '')
                //}
            //}
            steps {
                script{
                    sh """
                    #!/bin/bash
                    BLUE='\e[34m'
                    echo -e "${BLUE}INFO: Information goes here.${BLUE}"
                    """
                    echo "${table}"
                    def USER_INPUT = input(
                    message: 'User input required - Some Yes or No question?',
                    parameters: [
                            [$class: 'ChoiceParameterDefinition',
                             choices: ['no','yes'].join('\n'),
                             name: 'input',
                             description: 'Menu - select box option ']
                        
                    ])
                    echo "The answer is: ${USER_INPUT}"
                    if( "${USER_INPUT}" == "yes"){
                        //do something
                        echo "hello boss"
                    } else {
                        //do something else
                        echo "good morning"
                    }
                }
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}
