pipeline {
    agent any
    stages {
        stage('Example') {
            environment {
                choice = 'one'
                test = 'two'
            }
           // input {
             //   message "Should we continue?"
               // ok "Yes, we should."
                //submitter "alice,bob"
                //parameters {
                    //string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                  //  choice(name: 'CHOICES', choices: ['one', 'two'], description: '')
                //}
            //}
            steps {
                script{
                    def inputConfig
                    //def inputTest

                    // Get the input
                    def userInput = input(
                            id: 'userInput', message: 'Enter path of test reports:?',
                            parameters: [

                                    choice(choices: ['approve', 'reject'],
                                            description: 'Path of config file',
                                            name: 'Config'),
                            ])

                    // Save to variables. Default to empty string if not found.
                    inputConfig = userInput.Config?:''
                   // inputTest = userInput.Test?:''

                    // Echo to console
                    echo("${inputConfig}")
                    if(${inputConfig} == 'approve'){
                        echo "hi"
                    }
                }
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}
